package br.com.arirang.plataforma.service;

import br.com.arirang.plataforma.dto.AlunoDTO;
import br.com.arirang.plataforma.entity.Aluno;
import br.com.arirang.plataforma.entity.Responsavel;
import br.com.arirang.plataforma.entity.Turma;
import br.com.arirang.plataforma.repository.AlunoRepository;
import br.com.arirang.plataforma.repository.ResponsavelRepository;
import br.com.arirang.plataforma.repository.TurmaRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Service
public class AlunoService {

    private static final Logger logger = LoggerFactory.getLogger(AlunoService.class);

    @Autowired
    private AlunoRepository alunoRepository;

    @Autowired
    private ResponsavelRepository responsavelRepository;

    @Autowired
    private TurmaRepository turmaRepository;

    @PersistenceContext
    private EntityManager entityManager;

    public List<Aluno> listarTodosAlunos() {
        try {
            // Usando LEFT JOIN FETCH para buscar as associações e evitar o erro de lazy loading
            List<Aluno> alunos = entityManager.createQuery(
                            "SELECT DISTINCT a FROM Aluno a LEFT JOIN FETCH a.turmas LEFT JOIN FETCH a.responsavel", Aluno.class)
                    .getResultList();
            if (alunos.isEmpty()) {
                logger.warn("Nenhum aluno encontrado no banco de dados.");
            }
            return alunos;
        } catch (Exception e) {
            logger.error("Erro ao listar todos os alunos: ", e);
            throw new RuntimeException("Erro ao carregar os alunos: " + e.getMessage());
        }
    }

    public Optional<Aluno> buscarAlunoPorId(Long id) {
        try {
            return alunoRepository.findById(id);
        } catch (Exception e) {
            logger.error("Erro ao buscar aluno por ID {}: ", id, e);
            throw new RuntimeException("Erro ao buscar aluno: " + e.getMessage());
        }
    }

    @Transactional
    public Aluno criarAluno(AlunoDTO alunoDTO) {
        try {
            Aluno aluno = new Aluno();
            // ID is generated by the database, should not be set from DTO
            aluno.setNomeCompleto(alunoDTO.nomeCompleto());
            aluno.setEmail(alunoDTO.email());
            aluno.setCpf(alunoDTO.cpf());
            aluno.setRg(alunoDTO.rg());
            aluno.setOrgaoExpeditorRg(alunoDTO.orgaoExpeditorRg());
            aluno.setNacionalidade(alunoDTO.nacionalidade());
            aluno.setUf(alunoDTO.uf());
            aluno.setTelefone(alunoDTO.telefone());
            aluno.setDataNascimento(alunoDTO.dataNascimento()); // Direct assignment
            aluno.setNomeSocial(alunoDTO.nomeSocial());
            aluno.setGenero(alunoDTO.genero());
            aluno.setSituacao(alunoDTO.situacao());
            aluno.setUltimoNivel(alunoDTO.ultimoNivel());
            aluno.setEndereco(alunoDTO.endereco());
            aluno.setGrauParentesco(alunoDTO.grauParentesco());
            aluno.setResponsavelFinanceiro(alunoDTO.responsavelFinanceiro());

            if (alunoDTO.responsavelId() != null) {
                Responsavel responsavel = responsavelRepository.findById(alunoDTO.responsavelId())
                        .orElseThrow(() -> new RuntimeException("Responsável não encontrado com ID: " + alunoDTO.responsavelId()));
                aluno.setResponsavel(responsavel);
            }

            if (alunoDTO.turmaIds() != null && !alunoDTO.turmaIds().isEmpty()) {
                List<Turma> turmas = turmaRepository.findAllById(alunoDTO.turmaIds());
                aluno.setTurmas(turmas);
            }

            Aluno savedAluno = alunoRepository.save(aluno);
            logger.info("Aluno criado com ID: {}", savedAluno.getId());
            return savedAluno;
        } catch (Exception e) {
            logger.error("Erro ao criar aluno: ", e);
            throw new RuntimeException("Erro ao criar aluno: " + e.getMessage());
        }
    }

    @Transactional
    public Aluno atualizarAluno(Long id, AlunoDTO alunoDTO) {
        try {
            Aluno alunoExistente = alunoRepository.findById(id)
                    .orElseThrow(() -> new RuntimeException("Aluno não encontrado com ID: " + id));

            alunoExistente.setNomeCompleto(alunoDTO.nomeCompleto());
            alunoExistente.setEmail(alunoDTO.email());
            alunoExistente.setCpf(alunoDTO.cpf());
            alunoExistente.setRg(alunoDTO.rg());
            alunoExistente.setOrgaoExpeditorRg(alunoDTO.orgaoExpeditorRg());
            alunoExistente.setNacionalidade(alunoDTO.nacionalidade());
            alunoExistente.setUf(alunoDTO.uf());
            alunoExistente.setTelefone(alunoDTO.telefone());
            alunoExistente.setDataNascimento(alunoDTO.dataNascimento()); // Direct assignment
            alunoExistente.setNomeSocial(alunoDTO.nomeSocial());
            alunoExistente.setGenero(alunoDTO.genero());
            alunoExistente.setSituacao(alunoDTO.situacao());
            alunoExistente.setUltimoNivel(alunoDTO.ultimoNivel());
            alunoExistente.setEndereco(alunoDTO.endereco());
            alunoExistente.setGrauParentesco(alunoDTO.grauParentesco());
            alunoExistente.setResponsavelFinanceiro(alunoDTO.responsavelFinanceiro());

            if (alunoDTO.responsavelId() != null) {
                Responsavel responsavel = responsavelRepository.findById(alunoDTO.responsavelId())
                        .orElseThrow(() -> new RuntimeException("Responsável não encontrado com ID: " + alunoDTO.responsavelId()));
                alunoExistente.setResponsavel(responsavel);
            }

            if (alunoDTO.turmaIds() != null && !alunoDTO.turmaIds().isEmpty()) {
                List<Turma> turmas = turmaRepository.findAllById(alunoDTO.turmaIds());
                alunoExistente.setTurmas(turmas);
            } else {
                alunoExistente.getTurmas().clear();
            }

            Aluno updatedAluno = alunoRepository.save(alunoExistente);
            logger.info("Aluno atualizado com ID: {}", updatedAluno.getId());
            return updatedAluno;
        } catch (Exception e) {
            logger.error("Erro ao atualizar aluno com ID {}: ", id, e);
            throw new RuntimeException("Erro ao atualizar aluno: " + e.getMessage());
        }
    }

    @Transactional
    public void deletarAluno(Long id) {
        try {
            if (alunoRepository.existsById(id)) {
                alunoRepository.deleteById(id);
                logger.info("Aluno deletado com ID: {}", id);
            } else {
                throw new RuntimeException("Aluno não encontrado com ID: " + id);
            }
        } catch (Exception e) {
            logger.error("Erro ao deletar aluno com ID {}: ", id, e);
            throw new RuntimeException("Erro ao deletar aluno: " + e.getMessage());
        }
    }

    @Transactional
    public void associarTurma(Long alunoId, Long turmaId) {
        try {
            Aluno aluno = alunoRepository.findById(alunoId)
                    .orElseThrow(() -> new RuntimeException("Aluno não encontrado com ID: " + alunoId));
            Turma turma = turmaRepository.findById(turmaId)
                    .orElseThrow(() -> new RuntimeException("Turma não encontrada com ID: " + turmaId));

            if (aluno.getTurmas() == null) {
                aluno.setTurmas(new java.util.ArrayList<>());
            }
            
            if (aluno.getTurmas().stream().noneMatch(t -> t.getId().equals(turmaId))) {
                aluno.getTurmas().add(turma);
                alunoRepository.save(aluno);
                logger.info("Turma {} associada ao aluno {}", turmaId, alunoId);
            }
        } catch (Exception e) {
            logger.error("Erro ao associar turma {} ao aluno {}: ", turmaId, alunoId, e);
            throw new RuntimeException("Erro ao associar turma: " + e.getMessage());
        }
    }
}
